### ISSUE TITLE
Cannot load cursor theme

### ISSUE THREAD

**Issue by BachoSeven** [aleksator/arch-cursor-complete#2]
Hi! I tried to install this (from AUR), but I cannot get the cursor to load. I have set `Inherits=ArchCursorComplete` in `/usr/share/icons/default/index.theme`, but it does not work.. Before trying to manually symlink eventual missing icons from Adawaita as suggested by the [wiki](https://wiki.archlinux.org/index.php/Cursor_themes#Troubleshooting), I wanted to ask you if you think there is something I can do to fix it. I run Arch 64-bit with `dwm` as my window manager.

I also use `gruvbox-dark-gtk` and `gruvbox-dark-icons-gtk` for general icons and gtk theme, but I tried uninstalling the icons package and nothing changed.

**Comment by aleksator** [comment]
Hi @BachoSeven!

I've installed dwm to try it out and found that after creating a file `~/.Xresourses` containing the line
`Xcursor.theme: ArchCursorComplete`
the theme was successfully loaded (re-login is needed). 

I didn't do anything else (i.e. touching `Inherits` variable).

I found this solution under [X_resources](https://wiki.archlinux.org/index.php/Cursor_themes#X_resources) section on the wiki.

Let me know if this works for you!

**Comment by BachoSeven** [comment]
Hi again, I tried your solution but it also did not work for me.
What did work in the end was setting the `Inherits` under `~/.config/icons/default/index.theme`, which is weird because I think the standard user path is supposed to be `~/.icons`, but it seems someone implemented the XDG-Directory compliant path as well:)

Anyways, that works (I tried it because I used to do the same for another theme), but one needs to have the theme folder copied to .config/icons in order for it to work. Maybe you could add this as an alternative user-wide installation method, but feel free to close this anyway. Thank you for the package, the theme is quite neat!

**Comment by aleksator** [comment]
I see, this solution also exists in the wiki under [XDG](https://wiki.archlinux.org/index.php/Cursor_themes#XDG_specification) section.

You might also want to set
```
~/.config/gtk-3.0/settings.ini

[Settings]
gtk-cursor-theme-name=cursor_theme_name
```
as recommended there in case you get inconsistent cursor themes between QT and GTK applications.

Glad this works for you in the end, I'll update the Readme with the links to the Wiki.
